
import { Category } from './types';

export const COURSE_CATEGORIES_COLUMN_1: Category[] = [
  {
    id: 'cat1',
    title: 'OPERADOR DE COMPUTADOR PREMIUM',
    courses: [
      { id: 'c1_1', name: 'Windows10' },
      { id: 'c1_2', name: 'Word' },
      { id: 'c1_3', name: 'Excel' },
      { id: 'c1_4', name: 'Excel Avançado' },
      { id: 'c1_5', name: 'Power Point' },
      { id: 'c1_6', name: 'Armazenamento em Nuvem' },
      { id: 'c1_7', name: 'Aplicativos de Chamada' },
      { id: 'c1_8', name: 'Aplicativos de Acesso Remoto' },
      { id: 'c1_9', name: 'Introdução à Informática' },
      { id: 'c1_10', name: 'Digitação' },
    ],
  },
  {
    id: 'cat2',
    title: 'ESPECIALIDADES',
    courses: [
      { id: 'c2_1', name: 'Vitrinismo' },
      { id: 'c2_2', name: 'Operador de Drone' },
      { id: 'c2_3', name: 'Segurança Digital' },
      { id: 'c2_4', name: 'Marketing Digital' },
      { id: 'c2_5', name: 'Documentos Google' },
      { id: 'c2_6', name: 'Técnicas de Memorização' },
      { id: 'c2_7', name: 'Biossegurança' },
      { id: 'c2_8', name: 'Síndico de Condomínio' },
      { id: 'c2_9', name: 'Agente de Portaria' },
      { id: 'c2_10', name: 'Facebook Business' },
      { id: 'c2_11', name: 'Whatsapp Business' },
      { id: 'c2_12', name: 'Cuidador de Idosos' },
      { id: 'c2_13', name: 'Informática para Idosos' },
      { id: 'c2_14', name: 'Mídias Sociais' },
    ],
  },
  {
    id: 'cat3',
    title: 'CURSOS PROFISSIONALIZANTES',
    courses: [
      { id: 'c3_1', name: 'Atendente de Farmácia' },
      { id: 'c3_2', name: 'Hotelaria e Turismo' },
      { id: 'c3_3', name: 'Elaboração de Currículo' },
      { id: 'c3_4', name: 'Meu Novo Emprego' },
      { id: 'c3_5', name: 'Manutenção de Computadores' },
      { id: 'c3_6', name: 'Operador de Caixa' },
      { id: 'c3_7', name: 'Técnicas de Vendas' },
      { id: 'c3_8', name: 'Telemarketing' },
      { id: 'c3_9', name: 'Adobe Premiere Pro' },
    ],
  },
  {
    id: 'cat4',
    title: 'DESENVOLVEDOR E TECNOLOGIAS',
    courses: [
      { id: 'c4_1', name: 'Lógica de Programação' },
      { id: 'c4_2', name: 'Programação em PHP' },
      { id: 'c4_3', name: 'HTML e CSS' },
      { id: 'c4_4', name: 'Domínio' },
      { id: 'c4_5', name: 'Criador de Conteúdo Kids' },
      { id: 'c4_6', name: 'Inteligência Artificial' },
      { id: 'c4_7', name: 'Ambientes Digitais' },
      { id: 'c4_8', name: 'Empreendendo com Inteligência: AI nos Negócios' },
      { id: 'c4_9', name: 'Desenvolvedor de Aplicativos para Android' },
      { id: 'c4_10', name: 'Chat GPT' },
      { id: 'c4_11', name: 'Java Básico' },
      { id: 'c4_12', name: 'Python' },
      { id: 'c4_13', name: 'Programação Kids' },
      { id: 'c4_14', name: 'Wordpress' },
      { id: 'c4_15', name: 'Google Education Básico' },
      { id: 'c4_16', name: 'Google Education Avançado' },
      { id: 'c4_17', name: 'Youtuber' },
    ],
  },
];

export const COURSE_CATEGORIES_COLUMN_2: Category[] = [
  {
    id: 'cat5',
    title: 'CURSOS ADMINISTRATIVOS',
    courses: [
      { id: 'c5_1', name: 'Administrativo' },
      { id: 'c5_2', name: 'Gestão em RH' },
      { id: 'c5_3', name: 'Liderança Eficaz' },
      { id: 'c5_4', name: 'Empreendedorismo' },
      { id: 'c5_5', name: 'Administrativo Informatizado' },
      { id: 'c5_6', name: 'Crédito, Cobrança e Atendimento' },
      { id: 'c5_7', name: 'Logística' },
      { id: 'c5_8', name: 'Matemática Financeira com HP12C' },
      { id: 'c5_9', name: 'Normas da ABNT para trabalhos acadêmicos' },
      { id: 'c5_10', name: 'Assistente Contábil' },
      { id: 'c5_11', name: 'Departamento Pessoal' },
      { id: 'c5_12', name: 'Gestão Administrativa' },
      { id: 'c5_13', name: 'Marketing Pessoal' },
    ],
  },
  {
    id: 'cat6',
    title: 'DESIGNER GRÁFICO',
    courses: [
      { id: 'c6_1', name: 'Adobe Illustrator' },
      { id: 'c6_2', name: 'CorelDraw X8' },
      { id: 'c6_3', name: 'Indesign' },
      { id: 'c6_4', name: 'Photoshop' },
      { id: 'c6_5', name: 'Canva' },
    ],
  },
  {
    id: 'cat7',
    title: 'COMPUTAÇÃO GRÁFICA',
    courses: [
      { id: 'c7_1', name: '3D Studio Max' },
      { id: 'c7_2', name: 'After Effects' },
      { id: 'c7_3', name: 'AutoCad 2D' },
      { id: 'c7_4', name: 'AutoCad 3D' },
      { id: 'c7_5', name: 'SketchUp' },
      { id: 'c7_6', name: 'Multimídia' },
      { id: 'c7_7', name: 'Revit' },
    ],
  },
  {
    id: 'cat8',
    title: 'PERSONALIZADOS',
    courses: [
      { id: 'c8_1', name: 'Internet' },
      { id: 'c8_2', name: 'Internet Kids' },
      { id: 'c8_3', name: 'Windows 10 Kids' },
      { id: 'c8_4', name: 'Word Kids' },
      { id: 'c8_5', name: 'Power BI Desktop' },
    ],
  },
  {
    id: 'cat9',
    title: 'GAMES',
    courses: [
      { id: 'c9_1', name: 'Desenvolvedor de Games 3D - Módulo I' },
      { id: 'c9_2', name: 'Desenvolvedor de Games 3D - Módulo II' },
      { id: 'c9_3', name: 'Desenvolvedor de Games 3D - Módulo III' },
      { id: 'c9_4', name: 'Desenvolvedor de Games Online' },
      { id: 'c9_5', name: 'Desenvolvedor de Games Kids' },
    ],
  },
];
    